import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#e7c268",
        "tertiary-fixed-dim": "#ffb4a2",
        "surface-dim": "#dddbc8",
        "primary-fixed": "#ffdf96",
        "tertiary-container": "#ffb7a5",
        "surface-bright": "#fdfae7",
        "primary-container": "#e9c46a",
        "surface-variant": "#e6e3d0",
        "outline": "#7f7666",
        "on-secondary-fixed-variant": "#2d4f25",
        "on-background": "#1c1c11",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "surface-container-low": "#f7f4e1",
        "error-container": "#ffdad6",
        "secondary-container": "#c2ebb2",
        "on-primary": "#ffffff",
        "surface": "#fdfae7",
        "primary": "#765a05",
        "tertiary-fixed": "#ffdad2",
        "surface-container-highest": "#e6e3d0",
        "primary-fixed-dim": "#e7c268",
        "secondary": "#44673a",
        "on-primary-container": "#695000",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#83260e",
        "on-primary-fixed": "#251a00",
        "on-tertiary-container": "#95331a",
        "on-tertiary-fixed": "#3c0700",
        "surface-container": "#f1eedb",
        "surface-tint": "#765a05",
        "on-secondary-fixed": "#012201",
        "secondary-fixed": "#c5eeb5",
        "outline-variant": "#d0c5b2",
        "on-surface": "#1c1c11",
        "on-secondary-container": "#486b3e",
        "tertiary": "#a33d23",
        "on-primary-fixed-variant": "#5a4400",
        "inverse-surface": "#313124",
        "inverse-on-surface": "#f4f1de",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#4d4638",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#a9d29b",
        "background": "#fdfae7",
        "surface-container-high": "#ece9d6",
      },
      spacing: {
        "container-margin": "20px",
        "xl": "64px",
        "sm": "12px",
        "gutter": "16px",
        "md": "24px",
        "base": "8px",
        "xs": "4px",
        "lg": "48px",
      },
      fontFamily: {
        "body-lg": ["var(--font-plus-jakarta-sans)", "sans-serif"],
        "label-pixel": ["monospace"],
        "display-xl": ["var(--font-space-grotesk)", "sans-serif"],
        "headline-lg": ["var(--font-space-grotesk)", "sans-serif"],
        "headline-md": ["var(--font-space-grotesk)", "sans-serif"],
        "body-md": ["var(--font-plus-jakarta-sans)", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-pixel": ["14px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "700" }],
        "display-xl": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
export default config;
